#!/usr/bin/env python3
"""AC-to-test coverage report.

Scans `tests/` for `AC-*` id references and cross-checks them against the
canonical set discovered in `spec/21-app/` and `spec/23-app-db/`. Prints a
Markdown report to stdout suitable for redirecting to
`spec/25-app-audit/23-ac-test-coverage.md`.

This script is a REPORTER, not a gate. It always exits 0 unless the tests
folder references an AC id that does not exist in any spec (which IS a
defect worth failing on).

Usage:
    python3 linter-scripts/ac-test-coverage.py > spec/25-app-audit/23-ac-test-coverage.md
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SEARCH_ROOTS = [REPO / "spec" / "21-app", REPO / "spec" / "23-app-db"]
TESTS_ROOT = REPO / "tests"
INDEX_PATH = REPO / "spec" / "21-app" / "97-acceptance-criteria.md"
AC_RE = re.compile(r"AC-[A-Z]+-[0-9]+")


def collect_spec_ids() -> set[str]:
    ids: set[str] = set()
    for root in SEARCH_ROOTS:
        for path in root.rglob("*.md"):
            if path.resolve() == INDEX_PATH.resolve():
                continue
            ids.update(AC_RE.findall(path.read_text(encoding="utf-8", errors="replace")))
    return ids


def collect_test_ids() -> dict[str, set[str]]:
    by_file: dict[str, set[str]] = defaultdict(set)
    if not TESTS_ROOT.exists():
        return by_file
    for path in TESTS_ROOT.rglob("*"):
        if not path.is_file() or path.suffix not in {".ts", ".tsx"}:
            continue
        ids = set(AC_RE.findall(path.read_text(encoding="utf-8", errors="replace")))
        if ids:
            by_file[path.relative_to(REPO).as_posix()].update(ids)
    return by_file


def group_by_prefix(ids: set[str]) -> dict[str, set[str]]:
    grouped: dict[str, set[str]] = defaultdict(set)
    for ac in ids:
        prefix = ac.rsplit("-", 1)[0]  # AC-RL-008 -> AC-RL
        grouped[prefix].add(ac)
    return grouped


def main() -> int:
    spec_ids = collect_spec_ids()
    test_by_file = collect_test_ids()
    tested_ids: set[str] = set().union(*test_by_file.values()) if test_by_file else set()

    unknown = sorted(tested_ids - spec_ids)
    covered = sorted(tested_ids & spec_ids)
    missing = sorted(spec_ids - tested_ids)

    pct = (len(covered) / len(spec_ids) * 100.0) if spec_ids else 0.0

    print("# AC to Test Coverage Report")
    print()
    print("Auto-generated by `linter-scripts/ac-test-coverage.py`. Do NOT hand-edit.")
    print()
    print("## Summary")
    print()
    print(f"- Spec AC ids (union of `spec/21-app/` + `spec/23-app-db/`, excluding index): **{len(spec_ids)}**")
    print(f"- AC ids referenced from `tests/`: **{len(tested_ids)}**")
    print(f"- Covered (referenced AND in spec): **{len(covered)}**")
    print(f"- Coverage: **{pct:.1f}%**")
    print(f"- Unknown test refs (in tests but NOT in spec): **{len(unknown)}**")
    print()
    if unknown:
        print("## Unknown references (defect, must fix)")
        print()
        for ac in unknown:
            owners = [rel for rel, ids in test_by_file.items() if ac in ids]
            print(f"- `{ac}` referenced in {', '.join(f'`{o}`' for o in owners)}")
        print()

    print("## Covered by prefix")
    print()
    grouped_spec = group_by_prefix(spec_ids)
    grouped_test = group_by_prefix(set(covered))
    print("| Prefix | In spec | Covered | Percent |")
    print("| --- | ---: | ---: | ---: |")
    for prefix in sorted(grouped_spec):
        s = len(grouped_spec[prefix])
        t = len(grouped_test.get(prefix, set()))
        pp = (t / s * 100.0) if s else 0.0
        print(f"| `{prefix}` | {s} | {t} | {pp:.0f}% |")
    print()

    print("## Test references (canonical)")
    print()
    for rel in sorted(test_by_file):
        print(f"### `{rel}`")
        for ac in sorted(test_by_file[rel]):
            marker = "" if ac in spec_ids else "  **(UNKNOWN)**"
            print(f"- `{ac}`{marker}")
        print()

    return 1 if unknown else 0


if __name__ == "__main__":
    sys.exit(main())
