#!/usr/bin/env python3
"""
Plan 16 Step 17: ban `import.meta.env.MODE` outside the runtime-mode module.

Root cause guarded: Vite substitutes `import.meta.env.MODE` at build time
from the Vite build mode. After Plan 16 Steps 13-16 the authoritative
runtime mode is the frozen store in `src/lib/runtime-mode.ts`, seeded from
`public/version.json` and the P-02 localStorage override. Any feature
module that still reads `import.meta.env.MODE` bypasses the store, so the
compile-time value and the runtime value can disagree silently:
`isPreview()` returns `true` while `import.meta.env.MODE === "production"`,
UI branches diverge, and the whole point of the runtime-mode subsystem
collapses into decorative code.

This linter forbids the exact literal `import.meta.env.MODE` in every
TypeScript / TSX source under `src/` except the two allow-listed owners:

  - `src/lib/runtime-mode.ts`   : the resolver + frozen store (may need
    to reference the Vite build mode for the compile-time default in
    future revisions; currently it does not, but reserved).
  - `src/lib/version-json-loader.ts` : the single allow-listed writer of
    the P-02 override (reserved slot; not currently referenced).

`import.meta.env.DEV` and `import.meta.env.PROD` are deliberately NOT
banned. Those are boolean signals about the build (dev bundle vs
production bundle) used for `if (import.meta.env.DEV) throw ...` style
assertions (see `src/components/badge/registry.ts`,
`src/lib/closed-sets.ts`, `src/lib/error-messages.ts`), which is
orthogonal to the runtime `Mode` axis.

Exit code: 0 on clean scan, 1 on any violation. One line per finding so
CI logs point directly at the offending file:line.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"

# Only these modules may reference the Vite build mode literal directly.
ALLOWLIST = {
    "src/lib/runtime-mode.ts",
    "src/lib/version-json-loader.ts",
}

# Exact literal we want to forbid. We do NOT match `import.meta.env.DEV`
# or `.PROD`. The trailing `\b` prevents accidental matches on
# `MODEL`/`MODEL_ID` style identifiers that share a prefix.
PATTERN = re.compile(r"import\.meta\.env\.MODE\b")

# Extensions we scan. Route-tree generated file is skipped: it is
# auto-generated by the TanStack Router Vite plugin and must never be
# hand-edited.
SCAN_EXT = {".ts", ".tsx", ".js", ".jsx", ".mts", ".cts"}
SKIP_FILES = {"src/routeTree.gen.ts"}


def is_scannable(path: Path) -> bool:
    if path.suffix not in SCAN_EXT:
        return False
    rel = path.relative_to(REPO_ROOT).as_posix()
    if rel in SKIP_FILES:
        return False
    return True


def scan_file(path: Path) -> list[tuple[int, str]]:
    rel = path.relative_to(REPO_ROOT).as_posix()
    if rel in ALLOWLIST:
        return []
    findings: list[tuple[int, str]] = []
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as err:
        # Surface, do not swallow. The Core rule bans silent failure.
        print(f"[check-runtime-mode-usage] read failed: {rel}: {err}", file=sys.stderr)
        return []
    for lineno, line in enumerate(text.splitlines(), start=1):
        # Skip line comments so the migration guide comment in
        # runtime-mode.ts and similar reference docs do not trip.
        stripped = line.lstrip()
        if stripped.startswith("//") or stripped.startswith("*"):
            continue
        if PATTERN.search(line):
            findings.append((lineno, line.rstrip()))
    return findings


def main() -> int:
    if not SRC_DIR.is_dir():
        print(f"[check-runtime-mode-usage] src/ not found at {SRC_DIR}", file=sys.stderr)
        return 1
    total = 0
    for path in sorted(SRC_DIR.rglob("*")):
        if not path.is_file() or not is_scannable(path):
            continue
        for lineno, line in scan_file(path):
            rel = path.relative_to(REPO_ROOT).as_posix()
            print(f"{rel}:{lineno}: banned `import.meta.env.MODE` -> use getRuntimeMode() / isPreview()")
            print(f"    {line}")
            total += 1
    if total > 0:
        print(
            f"[check-runtime-mode-usage] FAIL: {total} violation(s). "
            "Route all runtime-mode reads through src/lib/runtime-mode.ts.",
            file=sys.stderr,
        )
        return 1
    print("check-runtime-mode-usage: OK (no `import.meta.env.MODE` outside runtime-mode.ts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
