/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as E2eErrorHarnessRouteImport } from './routes/e2e.error-harness'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPortalUpdatesRouteImport } from './routes/_authenticated/portal.updates'
import { Route as AuthenticatedPortalHomeRouteImport } from './routes/_authenticated/portal.home'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSnapshotsRouteImport } from './routes/_authenticated/admin.snapshots'
import { Route as AuthenticatedAdminSerialsRouteImport } from './routes/_authenticated/admin.serials'
import { Route as AuthenticatedAdminRuntimeRouteImport } from './routes/_authenticated/admin.runtime'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminResellersRouteImport } from './routes/_authenticated/admin.resellers'
import { Route as AuthenticatedAdminQuotasRouteImport } from './routes/_authenticated/admin.quotas'
import { Route as AuthenticatedAdminQuotaRequestsRouteImport } from './routes/_authenticated/admin.quota-requests'
import { Route as AuthenticatedAdminErrorsRouteImport } from './routes/_authenticated/admin.errors'
import { Route as AuthenticatedAdminDesignRouteImport } from './routes/_authenticated/admin.design'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAppUpdatesRouteImport } from './routes/_authenticated/admin.app-updates'
import { Route as AuthenticatedAdminApiDocsRouteImport } from './routes/_authenticated/admin.api-docs'
import { Route as AuthenticatedResellerResellerIdIndexRouteImport } from './routes/_authenticated/reseller.$resellerId.index'
import { Route as AuthenticatedAdminSnapshotsIndexRouteImport } from './routes/_authenticated/admin.snapshots.index'
import { Route as AuthenticatedResellerResellerIdQuotaRequestsRouteImport } from './routes/_authenticated/reseller.$resellerId.quota-requests'
import { Route as AuthenticatedAdminUsersNewRouteImport } from './routes/_authenticated/admin.users.new'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'
import { Route as AuthenticatedAdminSnapshotsSnapshotIdRouteImport } from './routes/_authenticated/admin.snapshots.$snapshotId'
import { Route as AuthenticatedAdminResellersNewRouteImport } from './routes/_authenticated/admin.resellers.new'
import { Route as AuthenticatedAdminResellersResellerIdRouteImport } from './routes/_authenticated/admin.resellers.$resellerId'
import { Route as AuthenticatedAdminLicensesNewRouteImport } from './routes/_authenticated/admin.licenses.new'
import { Route as AuthenticatedAdminLicensesLicenseIdRouteImport } from './routes/_authenticated/admin.licenses.$licenseId'
import { Route as AuthenticatedAdminBackupImportRouteImport } from './routes/_authenticated/admin.backup.import'
import { Route as AuthenticatedAdminBackupExportRouteImport } from './routes/_authenticated/admin.backup.export'
import { Route as AuthenticatedResellerResellerIdLicensesIndexRouteImport } from './routes/_authenticated/reseller.$resellerId.licenses.index'
import { Route as AuthenticatedResellerResellerIdLicensesLicenseKeyRouteImport } from './routes/_authenticated/reseller.$resellerId.licenses.$licenseKey'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eErrorHarnessRoute = E2eErrorHarnessRouteImport.update({
  id: '/e2e/error-harness',
  path: '/e2e/error-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPortalUpdatesRoute =
  AuthenticatedPortalUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalHomeRoute = AuthenticatedPortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSnapshotsRoute =
  AuthenticatedAdminSnapshotsRouteImport.update({
    id: '/snapshots',
    path: '/snapshots',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSerialsRoute =
  AuthenticatedAdminSerialsRouteImport.update({
    id: '/serials',
    path: '/serials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRuntimeRoute =
  AuthenticatedAdminRuntimeRouteImport.update({
    id: '/runtime',
    path: '/runtime',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminResellersRoute =
  AuthenticatedAdminResellersRouteImport.update({
    id: '/resellers',
    path: '/resellers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuotasRoute =
  AuthenticatedAdminQuotasRouteImport.update({
    id: '/quotas',
    path: '/quotas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuotaRequestsRoute =
  AuthenticatedAdminQuotaRequestsRouteImport.update({
    id: '/quota-requests',
    path: '/quota-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminErrorsRoute =
  AuthenticatedAdminErrorsRouteImport.update({
    id: '/errors',
    path: '/errors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDesignRoute =
  AuthenticatedAdminDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAppUpdatesRoute =
  AuthenticatedAdminAppUpdatesRouteImport.update({
    id: '/app-updates',
    path: '/app-updates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApiDocsRoute =
  AuthenticatedAdminApiDocsRouteImport.update({
    id: '/api-docs',
    path: '/api-docs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedResellerResellerIdIndexRoute =
  AuthenticatedResellerResellerIdIndexRouteImport.update({
    id: '/reseller/$resellerId/',
    path: '/reseller/$resellerId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSnapshotsIndexRoute =
  AuthenticatedAdminSnapshotsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSnapshotsRoute,
  } as any)
const AuthenticatedResellerResellerIdQuotaRequestsRoute =
  AuthenticatedResellerResellerIdQuotaRequestsRouteImport.update({
    id: '/reseller/$resellerId/quota-requests',
    path: '/reseller/$resellerId/quota-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersNewRoute =
  AuthenticatedAdminUsersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminSnapshotsSnapshotIdRoute =
  AuthenticatedAdminSnapshotsSnapshotIdRouteImport.update({
    id: '/$snapshotId',
    path: '/$snapshotId',
    getParentRoute: () => AuthenticatedAdminSnapshotsRoute,
  } as any)
const AuthenticatedAdminResellersNewRoute =
  AuthenticatedAdminResellersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminResellersRoute,
  } as any)
const AuthenticatedAdminResellersResellerIdRoute =
  AuthenticatedAdminResellersResellerIdRouteImport.update({
    id: '/$resellerId',
    path: '/$resellerId',
    getParentRoute: () => AuthenticatedAdminResellersRoute,
  } as any)
const AuthenticatedAdminLicensesNewRoute =
  AuthenticatedAdminLicensesNewRouteImport.update({
    id: '/licenses/new',
    path: '/licenses/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLicensesLicenseIdRoute =
  AuthenticatedAdminLicensesLicenseIdRouteImport.update({
    id: '/licenses/$licenseId',
    path: '/licenses/$licenseId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupImportRoute =
  AuthenticatedAdminBackupImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminBackupRoute,
  } as any)
const AuthenticatedAdminBackupExportRoute =
  AuthenticatedAdminBackupExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedAdminBackupRoute,
  } as any)
const AuthenticatedResellerResellerIdLicensesIndexRoute =
  AuthenticatedResellerResellerIdLicensesIndexRouteImport.update({
    id: '/reseller/$resellerId/licenses/',
    path: '/reseller/$resellerId/licenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResellerResellerIdLicensesLicenseKeyRoute =
  AuthenticatedResellerResellerIdLicensesLicenseKeyRouteImport.update({
    id: '/reseller/$resellerId/licenses/$licenseKey',
    path: '/reseller/$resellerId/licenses/$licenseKey',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/e2e/error-harness': typeof E2eErrorHarnessRoute
  '/admin/api-docs': typeof AuthenticatedAdminApiDocsRoute
  '/admin/app-updates': typeof AuthenticatedAdminAppUpdatesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRouteWithChildren
  '/admin/design': typeof AuthenticatedAdminDesignRoute
  '/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/admin/quota-requests': typeof AuthenticatedAdminQuotaRequestsRoute
  '/admin/quotas': typeof AuthenticatedAdminQuotasRoute
  '/admin/resellers': typeof AuthenticatedAdminResellersRouteWithChildren
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/runtime': typeof AuthenticatedAdminRuntimeRoute
  '/admin/serials': typeof AuthenticatedAdminSerialsRoute
  '/admin/snapshots': typeof AuthenticatedAdminSnapshotsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/portal/home': typeof AuthenticatedPortalHomeRoute
  '/portal/updates': typeof AuthenticatedPortalUpdatesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/backup/export': typeof AuthenticatedAdminBackupExportRoute
  '/admin/backup/import': typeof AuthenticatedAdminBackupImportRoute
  '/admin/licenses/$licenseId': typeof AuthenticatedAdminLicensesLicenseIdRoute
  '/admin/licenses/new': typeof AuthenticatedAdminLicensesNewRoute
  '/admin/resellers/$resellerId': typeof AuthenticatedAdminResellersResellerIdRoute
  '/admin/resellers/new': typeof AuthenticatedAdminResellersNewRoute
  '/admin/snapshots/$snapshotId': typeof AuthenticatedAdminSnapshotsSnapshotIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/reseller/$resellerId/quota-requests': typeof AuthenticatedResellerResellerIdQuotaRequestsRoute
  '/admin/snapshots/': typeof AuthenticatedAdminSnapshotsIndexRoute
  '/reseller/$resellerId/': typeof AuthenticatedResellerResellerIdIndexRoute
  '/reseller/$resellerId/licenses/$licenseKey': typeof AuthenticatedResellerResellerIdLicensesLicenseKeyRoute
  '/reseller/$resellerId/licenses/': typeof AuthenticatedResellerResellerIdLicensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/e2e/error-harness': typeof E2eErrorHarnessRoute
  '/admin/api-docs': typeof AuthenticatedAdminApiDocsRoute
  '/admin/app-updates': typeof AuthenticatedAdminAppUpdatesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRouteWithChildren
  '/admin/design': typeof AuthenticatedAdminDesignRoute
  '/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/admin/quota-requests': typeof AuthenticatedAdminQuotaRequestsRoute
  '/admin/quotas': typeof AuthenticatedAdminQuotasRoute
  '/admin/resellers': typeof AuthenticatedAdminResellersRouteWithChildren
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/runtime': typeof AuthenticatedAdminRuntimeRoute
  '/admin/serials': typeof AuthenticatedAdminSerialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/portal/home': typeof AuthenticatedPortalHomeRoute
  '/portal/updates': typeof AuthenticatedPortalUpdatesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/backup/export': typeof AuthenticatedAdminBackupExportRoute
  '/admin/backup/import': typeof AuthenticatedAdminBackupImportRoute
  '/admin/licenses/$licenseId': typeof AuthenticatedAdminLicensesLicenseIdRoute
  '/admin/licenses/new': typeof AuthenticatedAdminLicensesNewRoute
  '/admin/resellers/$resellerId': typeof AuthenticatedAdminResellersResellerIdRoute
  '/admin/resellers/new': typeof AuthenticatedAdminResellersNewRoute
  '/admin/snapshots/$snapshotId': typeof AuthenticatedAdminSnapshotsSnapshotIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/reseller/$resellerId/quota-requests': typeof AuthenticatedResellerResellerIdQuotaRequestsRoute
  '/admin/snapshots': typeof AuthenticatedAdminSnapshotsIndexRoute
  '/reseller/$resellerId': typeof AuthenticatedResellerResellerIdIndexRoute
  '/reseller/$resellerId/licenses/$licenseKey': typeof AuthenticatedResellerResellerIdLicensesLicenseKeyRoute
  '/reseller/$resellerId/licenses': typeof AuthenticatedResellerResellerIdLicensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/e2e/error-harness': typeof E2eErrorHarnessRoute
  '/_authenticated/admin/api-docs': typeof AuthenticatedAdminApiDocsRoute
  '/_authenticated/admin/app-updates': typeof AuthenticatedAdminAppUpdatesRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRouteWithChildren
  '/_authenticated/admin/design': typeof AuthenticatedAdminDesignRoute
  '/_authenticated/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/_authenticated/admin/quota-requests': typeof AuthenticatedAdminQuotaRequestsRoute
  '/_authenticated/admin/quotas': typeof AuthenticatedAdminQuotasRoute
  '/_authenticated/admin/resellers': typeof AuthenticatedAdminResellersRouteWithChildren
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/runtime': typeof AuthenticatedAdminRuntimeRoute
  '/_authenticated/admin/serials': typeof AuthenticatedAdminSerialsRoute
  '/_authenticated/admin/snapshots': typeof AuthenticatedAdminSnapshotsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/portal/home': typeof AuthenticatedPortalHomeRoute
  '/_authenticated/portal/updates': typeof AuthenticatedPortalUpdatesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/backup/export': typeof AuthenticatedAdminBackupExportRoute
  '/_authenticated/admin/backup/import': typeof AuthenticatedAdminBackupImportRoute
  '/_authenticated/admin/licenses/$licenseId': typeof AuthenticatedAdminLicensesLicenseIdRoute
  '/_authenticated/admin/licenses/new': typeof AuthenticatedAdminLicensesNewRoute
  '/_authenticated/admin/resellers/$resellerId': typeof AuthenticatedAdminResellersResellerIdRoute
  '/_authenticated/admin/resellers/new': typeof AuthenticatedAdminResellersNewRoute
  '/_authenticated/admin/snapshots/$snapshotId': typeof AuthenticatedAdminSnapshotsSnapshotIdRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/_authenticated/reseller/$resellerId/quota-requests': typeof AuthenticatedResellerResellerIdQuotaRequestsRoute
  '/_authenticated/admin/snapshots/': typeof AuthenticatedAdminSnapshotsIndexRoute
  '/_authenticated/reseller/$resellerId/': typeof AuthenticatedResellerResellerIdIndexRoute
  '/_authenticated/reseller/$resellerId/licenses/$licenseKey': typeof AuthenticatedResellerResellerIdLicensesLicenseKeyRoute
  '/_authenticated/reseller/$resellerId/licenses/': typeof AuthenticatedResellerResellerIdLicensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/portal'
    | '/admin/login'
    | '/e2e/error-harness'
    | '/admin/api-docs'
    | '/admin/app-updates'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/design'
    | '/admin/errors'
    | '/admin/quota-requests'
    | '/admin/quotas'
    | '/admin/resellers'
    | '/admin/roles'
    | '/admin/runtime'
    | '/admin/serials'
    | '/admin/snapshots'
    | '/admin/users'
    | '/portal/home'
    | '/portal/updates'
    | '/admin/'
    | '/admin/backup/export'
    | '/admin/backup/import'
    | '/admin/licenses/$licenseId'
    | '/admin/licenses/new'
    | '/admin/resellers/$resellerId'
    | '/admin/resellers/new'
    | '/admin/snapshots/$snapshotId'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/reseller/$resellerId/quota-requests'
    | '/admin/snapshots/'
    | '/reseller/$resellerId/'
    | '/reseller/$resellerId/licenses/$licenseKey'
    | '/reseller/$resellerId/licenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/portal'
    | '/admin/login'
    | '/e2e/error-harness'
    | '/admin/api-docs'
    | '/admin/app-updates'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/design'
    | '/admin/errors'
    | '/admin/quota-requests'
    | '/admin/quotas'
    | '/admin/resellers'
    | '/admin/roles'
    | '/admin/runtime'
    | '/admin/serials'
    | '/admin/users'
    | '/portal/home'
    | '/portal/updates'
    | '/admin'
    | '/admin/backup/export'
    | '/admin/backup/import'
    | '/admin/licenses/$licenseId'
    | '/admin/licenses/new'
    | '/admin/resellers/$resellerId'
    | '/admin/resellers/new'
    | '/admin/snapshots/$snapshotId'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/reseller/$resellerId/quota-requests'
    | '/admin/snapshots'
    | '/reseller/$resellerId'
    | '/reseller/$resellerId/licenses/$licenseKey'
    | '/reseller/$resellerId/licenses'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/admin/login'
    | '/e2e/error-harness'
    | '/_authenticated/admin/api-docs'
    | '/_authenticated/admin/app-updates'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/design'
    | '/_authenticated/admin/errors'
    | '/_authenticated/admin/quota-requests'
    | '/_authenticated/admin/quotas'
    | '/_authenticated/admin/resellers'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/runtime'
    | '/_authenticated/admin/serials'
    | '/_authenticated/admin/snapshots'
    | '/_authenticated/admin/users'
    | '/_authenticated/portal/home'
    | '/_authenticated/portal/updates'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/backup/export'
    | '/_authenticated/admin/backup/import'
    | '/_authenticated/admin/licenses/$licenseId'
    | '/_authenticated/admin/licenses/new'
    | '/_authenticated/admin/resellers/$resellerId'
    | '/_authenticated/admin/resellers/new'
    | '/_authenticated/admin/snapshots/$snapshotId'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/admin/users/new'
    | '/_authenticated/reseller/$resellerId/quota-requests'
    | '/_authenticated/admin/snapshots/'
    | '/_authenticated/reseller/$resellerId/'
    | '/_authenticated/reseller/$resellerId/licenses/$licenseKey'
    | '/_authenticated/reseller/$resellerId/licenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  E2eErrorHarnessRoute: typeof E2eErrorHarnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/error-harness': {
      id: '/e2e/error-harness'
      path: '/e2e/error-harness'
      fullPath: '/e2e/error-harness'
      preLoaderRoute: typeof E2eErrorHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/updates': {
      id: '/_authenticated/portal/updates'
      path: '/updates'
      fullPath: '/portal/updates'
      preLoaderRoute: typeof AuthenticatedPortalUpdatesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/home': {
      id: '/_authenticated/portal/home'
      path: '/home'
      fullPath: '/portal/home'
      preLoaderRoute: typeof AuthenticatedPortalHomeRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/snapshots': {
      id: '/_authenticated/admin/snapshots'
      path: '/snapshots'
      fullPath: '/admin/snapshots'
      preLoaderRoute: typeof AuthenticatedAdminSnapshotsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/serials': {
      id: '/_authenticated/admin/serials'
      path: '/serials'
      fullPath: '/admin/serials'
      preLoaderRoute: typeof AuthenticatedAdminSerialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/runtime': {
      id: '/_authenticated/admin/runtime'
      path: '/runtime'
      fullPath: '/admin/runtime'
      preLoaderRoute: typeof AuthenticatedAdminRuntimeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resellers': {
      id: '/_authenticated/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AuthenticatedAdminResellersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quotas': {
      id: '/_authenticated/admin/quotas'
      path: '/quotas'
      fullPath: '/admin/quotas'
      preLoaderRoute: typeof AuthenticatedAdminQuotasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quota-requests': {
      id: '/_authenticated/admin/quota-requests'
      path: '/quota-requests'
      fullPath: '/admin/quota-requests'
      preLoaderRoute: typeof AuthenticatedAdminQuotaRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/errors': {
      id: '/_authenticated/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AuthenticatedAdminErrorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/design': {
      id: '/_authenticated/admin/design'
      path: '/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AuthenticatedAdminDesignRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/app-updates': {
      id: '/_authenticated/admin/app-updates'
      path: '/app-updates'
      fullPath: '/admin/app-updates'
      preLoaderRoute: typeof AuthenticatedAdminAppUpdatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-docs': {
      id: '/_authenticated/admin/api-docs'
      path: '/api-docs'
      fullPath: '/admin/api-docs'
      preLoaderRoute: typeof AuthenticatedAdminApiDocsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/reseller/$resellerId/': {
      id: '/_authenticated/reseller/$resellerId/'
      path: '/reseller/$resellerId'
      fullPath: '/reseller/$resellerId/'
      preLoaderRoute: typeof AuthenticatedResellerResellerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/snapshots/': {
      id: '/_authenticated/admin/snapshots/'
      path: '/'
      fullPath: '/admin/snapshots/'
      preLoaderRoute: typeof AuthenticatedAdminSnapshotsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSnapshotsRoute
    }
    '/_authenticated/reseller/$resellerId/quota-requests': {
      id: '/_authenticated/reseller/$resellerId/quota-requests'
      path: '/reseller/$resellerId/quota-requests'
      fullPath: '/reseller/$resellerId/quota-requests'
      preLoaderRoute: typeof AuthenticatedResellerResellerIdQuotaRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/new': {
      id: '/_authenticated/admin/users/new'
      path: '/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthenticatedAdminUsersNewRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/snapshots/$snapshotId': {
      id: '/_authenticated/admin/snapshots/$snapshotId'
      path: '/$snapshotId'
      fullPath: '/admin/snapshots/$snapshotId'
      preLoaderRoute: typeof AuthenticatedAdminSnapshotsSnapshotIdRouteImport
      parentRoute: typeof AuthenticatedAdminSnapshotsRoute
    }
    '/_authenticated/admin/resellers/new': {
      id: '/_authenticated/admin/resellers/new'
      path: '/new'
      fullPath: '/admin/resellers/new'
      preLoaderRoute: typeof AuthenticatedAdminResellersNewRouteImport
      parentRoute: typeof AuthenticatedAdminResellersRoute
    }
    '/_authenticated/admin/resellers/$resellerId': {
      id: '/_authenticated/admin/resellers/$resellerId'
      path: '/$resellerId'
      fullPath: '/admin/resellers/$resellerId'
      preLoaderRoute: typeof AuthenticatedAdminResellersResellerIdRouteImport
      parentRoute: typeof AuthenticatedAdminResellersRoute
    }
    '/_authenticated/admin/licenses/new': {
      id: '/_authenticated/admin/licenses/new'
      path: '/licenses/new'
      fullPath: '/admin/licenses/new'
      preLoaderRoute: typeof AuthenticatedAdminLicensesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/licenses/$licenseId': {
      id: '/_authenticated/admin/licenses/$licenseId'
      path: '/licenses/$licenseId'
      fullPath: '/admin/licenses/$licenseId'
      preLoaderRoute: typeof AuthenticatedAdminLicensesLicenseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup/import': {
      id: '/_authenticated/admin/backup/import'
      path: '/import'
      fullPath: '/admin/backup/import'
      preLoaderRoute: typeof AuthenticatedAdminBackupImportRouteImport
      parentRoute: typeof AuthenticatedAdminBackupRoute
    }
    '/_authenticated/admin/backup/export': {
      id: '/_authenticated/admin/backup/export'
      path: '/export'
      fullPath: '/admin/backup/export'
      preLoaderRoute: typeof AuthenticatedAdminBackupExportRouteImport
      parentRoute: typeof AuthenticatedAdminBackupRoute
    }
    '/_authenticated/reseller/$resellerId/licenses/': {
      id: '/_authenticated/reseller/$resellerId/licenses/'
      path: '/reseller/$resellerId/licenses'
      fullPath: '/reseller/$resellerId/licenses/'
      preLoaderRoute: typeof AuthenticatedResellerResellerIdLicensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reseller/$resellerId/licenses/$licenseKey': {
      id: '/_authenticated/reseller/$resellerId/licenses/$licenseKey'
      path: '/reseller/$resellerId/licenses/$licenseKey'
      fullPath: '/reseller/$resellerId/licenses/$licenseKey'
      preLoaderRoute: typeof AuthenticatedResellerResellerIdLicensesLicenseKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminBackupRouteChildren {
  AuthenticatedAdminBackupExportRoute: typeof AuthenticatedAdminBackupExportRoute
  AuthenticatedAdminBackupImportRoute: typeof AuthenticatedAdminBackupImportRoute
}

const AuthenticatedAdminBackupRouteChildren: AuthenticatedAdminBackupRouteChildren =
  {
    AuthenticatedAdminBackupExportRoute: AuthenticatedAdminBackupExportRoute,
    AuthenticatedAdminBackupImportRoute: AuthenticatedAdminBackupImportRoute,
  }

const AuthenticatedAdminBackupRouteWithChildren =
  AuthenticatedAdminBackupRoute._addFileChildren(
    AuthenticatedAdminBackupRouteChildren,
  )

interface AuthenticatedAdminResellersRouteChildren {
  AuthenticatedAdminResellersResellerIdRoute: typeof AuthenticatedAdminResellersResellerIdRoute
  AuthenticatedAdminResellersNewRoute: typeof AuthenticatedAdminResellersNewRoute
}

const AuthenticatedAdminResellersRouteChildren: AuthenticatedAdminResellersRouteChildren =
  {
    AuthenticatedAdminResellersResellerIdRoute:
      AuthenticatedAdminResellersResellerIdRoute,
    AuthenticatedAdminResellersNewRoute: AuthenticatedAdminResellersNewRoute,
  }

const AuthenticatedAdminResellersRouteWithChildren =
  AuthenticatedAdminResellersRoute._addFileChildren(
    AuthenticatedAdminResellersRouteChildren,
  )

interface AuthenticatedAdminSnapshotsRouteChildren {
  AuthenticatedAdminSnapshotsSnapshotIdRoute: typeof AuthenticatedAdminSnapshotsSnapshotIdRoute
  AuthenticatedAdminSnapshotsIndexRoute: typeof AuthenticatedAdminSnapshotsIndexRoute
}

const AuthenticatedAdminSnapshotsRouteChildren: AuthenticatedAdminSnapshotsRouteChildren =
  {
    AuthenticatedAdminSnapshotsSnapshotIdRoute:
      AuthenticatedAdminSnapshotsSnapshotIdRoute,
    AuthenticatedAdminSnapshotsIndexRoute:
      AuthenticatedAdminSnapshotsIndexRoute,
  }

const AuthenticatedAdminSnapshotsRouteWithChildren =
  AuthenticatedAdminSnapshotsRoute._addFileChildren(
    AuthenticatedAdminSnapshotsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersNewRoute: typeof AuthenticatedAdminUsersNewRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminUsersNewRoute: AuthenticatedAdminUsersNewRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApiDocsRoute: typeof AuthenticatedAdminApiDocsRoute
  AuthenticatedAdminAppUpdatesRoute: typeof AuthenticatedAdminAppUpdatesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRouteWithChildren
  AuthenticatedAdminDesignRoute: typeof AuthenticatedAdminDesignRoute
  AuthenticatedAdminErrorsRoute: typeof AuthenticatedAdminErrorsRoute
  AuthenticatedAdminQuotaRequestsRoute: typeof AuthenticatedAdminQuotaRequestsRoute
  AuthenticatedAdminQuotasRoute: typeof AuthenticatedAdminQuotasRoute
  AuthenticatedAdminResellersRoute: typeof AuthenticatedAdminResellersRouteWithChildren
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminRuntimeRoute: typeof AuthenticatedAdminRuntimeRoute
  AuthenticatedAdminSerialsRoute: typeof AuthenticatedAdminSerialsRoute
  AuthenticatedAdminSnapshotsRoute: typeof AuthenticatedAdminSnapshotsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLicensesLicenseIdRoute: typeof AuthenticatedAdminLicensesLicenseIdRoute
  AuthenticatedAdminLicensesNewRoute: typeof AuthenticatedAdminLicensesNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApiDocsRoute: AuthenticatedAdminApiDocsRoute,
  AuthenticatedAdminAppUpdatesRoute: AuthenticatedAdminAppUpdatesRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRouteWithChildren,
  AuthenticatedAdminDesignRoute: AuthenticatedAdminDesignRoute,
  AuthenticatedAdminErrorsRoute: AuthenticatedAdminErrorsRoute,
  AuthenticatedAdminQuotaRequestsRoute: AuthenticatedAdminQuotaRequestsRoute,
  AuthenticatedAdminQuotasRoute: AuthenticatedAdminQuotasRoute,
  AuthenticatedAdminResellersRoute:
    AuthenticatedAdminResellersRouteWithChildren,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminRuntimeRoute: AuthenticatedAdminRuntimeRoute,
  AuthenticatedAdminSerialsRoute: AuthenticatedAdminSerialsRoute,
  AuthenticatedAdminSnapshotsRoute:
    AuthenticatedAdminSnapshotsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminLicensesLicenseIdRoute:
    AuthenticatedAdminLicensesLicenseIdRoute,
  AuthenticatedAdminLicensesNewRoute: AuthenticatedAdminLicensesNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalHomeRoute: typeof AuthenticatedPortalHomeRoute
  AuthenticatedPortalUpdatesRoute: typeof AuthenticatedPortalUpdatesRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalHomeRoute: AuthenticatedPortalHomeRoute,
  AuthenticatedPortalUpdatesRoute: AuthenticatedPortalUpdatesRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedResellerResellerIdQuotaRequestsRoute: typeof AuthenticatedResellerResellerIdQuotaRequestsRoute
  AuthenticatedResellerResellerIdIndexRoute: typeof AuthenticatedResellerResellerIdIndexRoute
  AuthenticatedResellerResellerIdLicensesLicenseKeyRoute: typeof AuthenticatedResellerResellerIdLicensesLicenseKeyRoute
  AuthenticatedResellerResellerIdLicensesIndexRoute: typeof AuthenticatedResellerResellerIdLicensesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedResellerResellerIdQuotaRequestsRoute:
    AuthenticatedResellerResellerIdQuotaRequestsRoute,
  AuthenticatedResellerResellerIdIndexRoute:
    AuthenticatedResellerResellerIdIndexRoute,
  AuthenticatedResellerResellerIdLicensesLicenseKeyRoute:
    AuthenticatedResellerResellerIdLicensesLicenseKeyRoute,
  AuthenticatedResellerResellerIdLicensesIndexRoute:
    AuthenticatedResellerResellerIdLicensesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  E2eErrorHarnessRoute: E2eErrorHarnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
